- name: hackathon
  color: 'D4C5F9'
  description: Hackathon-related tasks and contributions
- name: tool
  color: '0E8A16'
  description: CLI tool additions or changes
- name: docs
  color: '1D76DB'
  description: Documentation updates
- name: tutorial
  color: '5319E7'
  description: Guided learning content
- name: enhancement
  color: 'A2EEEF'
  description: Feature requests or improvements
- name: bug
  color: 'D73A4A'
  description: Something isn't working
- name: good first issue
  color: '7057FF'
  description: Good for newcomers
- name: help wanted
  color: '008672'
  description: Extra attention is needed
- name: ci
  color: 'BFD4F2'
  description: Continuous integration changes 