name: Seed Issues

on:
  workflow_dispatch: {}

jobs:
  create:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - name: Create issues from YAML
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const path = '.github/issues-seed.yml';
            const yaml = require('js-yaml');
            const content = fs.readFileSync(path, 'utf8');
            const data = yaml.load(content);
            for (const issue of data.issues) {
              await github.rest.issues.create({
                owner: context.repo.owner,
                repo: context.repo.repo,
                title: issue.title,
                labels: issue.labels,
                body: issue.body,
              });
            }
      - name: Install yaml parser
        run: npm i js-yaml 